version: '3'
services:
  couch:
    image: klaemo/couchdb
    ports:
    - "5984:5984"
  influx:
    image: influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
